# Sample LUKS Configuration
luks:
  volumePath: "/var/luks/udm-luks.img"
  mapperName: "udm-luks"
  mountPoint: "/mnt/udm-luks"
  passwordLength: 20
  size: 32
  useTPM: true
  user: "root"
  group: "root"